# Developer: Asman Mirza
# Email: rambo007.am@gmail.com
# Date: 24 January, 2024

version: '3'

services:
  zookeeper:
    container_name: zookeeper_one
    image: quay.io/debezium/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    container_name: kafka_one
    image: quay.io/debezium/kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka_data:/var/lib/kafka/data

  connect:
    container_name: debezium
    image: jdbc-debezium-connect:latest
    ports:
      - 8083:8083
    depends_on:
      - kafka
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - LD_LIBRARY_PATH=/instant_client
      - KAFKA_DEBUG=true
      - DEBUG_SUSPEND_FLAG=n
      - JAVA_DEBUG_PORT=0.0.0.0:5005

  kafka-ui:
    container_name: kafka-dash
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  oracle:
    container_name: oracle19e
    image: oracle/database:19.3.0-ee
    ports:
      - "1521:1521" # Oracle Port
      - "5500:5500" # OEM Express Port
    environment:
      - ORACLE_SID=TEST
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Design_25
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./oracle_scripts/startup:/docker-entrypoint-initdb.d/startup
      - ./oracle_scripts/setup:/docker-entrypoint-initdb.d/setup

networks:
  app-network:
    driver: bridge

volumes:
  kafka_data:
  oracle_data:
